apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: your-cluster-name
  region: your-region

nodeGroups:
  - name: ng-1
    instanceType: your-instance-type
    desiredCapacity: 3
    iam:
      withAddonPolicies:
        autoScaler: true
        albIngress: true
        ebs: true
        fsx: false
